services:

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - starwars-db:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    image: pjmagee/starwars-data-web
    ports:
      - "7051:7051"
      - "5051:5051"
    entrypoint: ["dotnet", "StarWarsData.Server.dll"]
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS: 7051
      ASPNETCORE_URLS: https://*:7051;http://*:5051
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      SWDATA_Settings__MongoConnectionString: mongodb://admin:password@database:27017
    volumes:
     - ~/.aspnet/https:/https:ro

  download:
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
    image: pjmagee/starwars-data-cli
    profiles: ["process"]
    entrypoint: ["dotnet", "StarWarsData.CLI.dll"]
    environment:
      DOTNET_ENVIRONMENT: Development
      SWDATA_Settings__DataDirectory: /data
      SWDATA_Settings__PageNamespace: 0
      SWDATA_Settings__PageLimit: 500
      SWDATA_Settings__PageStart: 1
      SWDATA_Settings__FirstPageOnly: false
    command: download
    volumes:
      # - starwars-data:/data
        - .\data:/data

  process:
    build: 
      context: .
      dockerfile: Dockerfile
      target: cli
    image: pjmagee/starwars-data-cli
    profiles: ["process"]
    entrypoint: ["dotnet", "StarWarsData.CLI.dll"]
    environment:
      DOTNET_ENVIRONMENT: Development
      SWDATA_Settings__DataDirectory: /data
    command: process
    volumes:
      # - starwars-data:/data
      - .\data:/data

  populate:
    build: 
      context: .
      dockerfile: Dockerfile
      target: cli
    image: pjmagee/starwars-data-cli:latest
    entrypoint: ["dotnet", "StarWarsData.CLI.dll"]
    environment:
      DOTNET_ENVIRONMENT: Development
      SWDATA_Settings__DataDirectory: /data
      SWDATA_Settings__MongoConnectionString: mongodb://admin:password@database:27017
    command: populate
    volumes:
      # - starwars-data:/data
      - .\data:/data

volumes:
  starwars-data:
  starwars-db: