using System.Globalization;
using Microsoft.Extensions.Logging; // Added for logging
using StarWarsData.Models.Mongo;
using StarWarsData.Models.Queries;
using StarWarsData.Services.Helpers;
using TimelineEvent = StarWarsData.Models.Mongo.TimelineEvent;

namespace StarWarsData.Services.Data;

public class RecordToEventsTransformer
{
    private readonly YearHelper _yearHelper;
    private readonly ILogger<RecordToEventsTransformer> _logger; // Added logger
    private readonly TemplateHelper _templateHelper; // Added TemplateHelper

    // Updated constructor to inject ILogger and TemplateHelper
    public RecordToEventsTransformer(YearHelper yearHelper, ILogger<RecordToEventsTransformer> logger, TemplateHelper templateHelper)
    {
        _yearHelper = yearHelper;
        _logger = logger;
        _templateHelper = templateHelper; // Assign injected helper
    }
    
    // Change the return type to IEnumerable<TimelineEventDocument>
    public IEnumerable<TimelineEvent> Transform(Record r)
    {
        foreach (var data in r.Data)
        {
            foreach (var link in data.Links.Where(_yearHelper.IsValidLink))
            {
                var year = ParseYear(link.Content); // Get nullable year

                // Skip if year parsing failed
                if (year == null)
                {
                    // Removed trailing period from log message again
                    _logger.LogWarning("Could not parse year from link content '{LinkContent}' for page '{PageTitle}'. Skipping this event", link.Content, r.PageTitle);
                    continue;
                }

                // Yield a TimelineEventDocument instead of TimelineEvent
                yield return new TimelineEvent
                {
                    Title = r.PageTitle,
                    DateEvent = GetDateEvent(data),
                    Demarcation = link.Content.Contains("ABY") ? Demarcation.Aby : link.Content.Contains("BBY") ? Demarcation.Bby : Demarcation.Unset,
                    Year = year.Value, // Use the parsed year value
                    Template = r.TemplateUrl, // Store the raw template URL/name
                    CleanedTemplate = _templateHelper.CleanTemplate(r.TemplateUrl), // Use helper method
                    ImageUrl = r.ImageUrl,
                    Properties = r.Data,
                    // Id will be generated by MongoDB
                };
            }
        }
    }

    private string? GetDateEvent(InfoboxProperty data) => data.Label switch
    {
        "Date" => String.Empty, _ => data.Label
    };

    // Updated to return float? and use TryParse
    private float? ParseYear(string text)
    {
        var yearString = new String(text.Split(' ', '-')[0].Where(c => !char.IsLetter(c)).ToArray());
        // Use InvariantCulture for consistent parsing regardless of system locale
        if (float.TryParse(yearString, NumberStyles.Any, CultureInfo.InvariantCulture, out float result))
        {
            return result;
        }
        _logger.LogWarning("Failed to parse year from text: {Text}", text); // Added logging for parse failure
        return null; // Return null if parsing fails
    }
}
