// Regenerates src/StarWarsData.Services/KnowledgeGraph/Definitions/TemplateFields.g.cs
// from the live MongoDB infobox data in starwars-dev.raw.pages.
//
// Groups documents by infobox template and emits a C# static dictionary mapping
// each template name → set of distinct field labels (count >= 5) that appear on
// pages of that template type. The generated file is consumed by
// InfoboxDefinitionRegistry to build template-scoped InfoboxDefinitions.
//
// Usage:
//   mongosh "$MDB_MCP_CONNECTION_STRING" --quiet --file eng/scripts/generate-template-fields.mongodb.js
//
// Or interactively in a mongosh session:
//   use starwars-dev
//   load("eng/scripts/generate-template-fields.mongodb.js")
//
// Tunable knobs (edit the constants below or override via shell):
//   DB_NAME         — database to inventory (default: starwars-dev)
//   MIN_COUNT       — minimum field occurrences to include (default: 1)
//                     Infobox field labels come from structured Fandom templates,
//                     so there's no "noise" to filter out — a field appearing once
//                     means it genuinely exists on that template. Only raise this
//                     if you explicitly want to exclude long-tail labels (e.g. to
//                     shrink the generated file for a specific analysis).
//   OUTPUT_PATH     — where to write the .g.cs file

const DB_NAME = globalThis.DB_NAME ?? "starwars-dev";
const COLL_NAME = globalThis.COLL_NAME ?? "raw.pages";
const MIN_COUNT = globalThis.MIN_COUNT ?? 1;
const OUTPUT_PATH =
    globalThis.OUTPUT_PATH
    ?? "src/StarWarsData.Services/KnowledgeGraph/Definitions/TemplateFields.g.cs";

print(`Connecting to ${DB_NAME}.${COLL_NAME}...`);
const coll = db.getSiblingDB(DB_NAME).getCollection(COLL_NAME);

print("Running aggregation...");
const results = coll
    .aggregate(
        [
            {
                $match: {
                    rawInfobox: { $exists: true },
                    "infobox.Template": { $ne: null },
                },
            },
            {
                $project: {
                    template: {
                        $arrayElemAt: [
                            { $split: ["$infobox.Template", "Template:"] },
                            1,
                        ],
                    },
                    labels: "$infobox.Data.Label",
                },
            },
            { $unwind: "$labels" },
            { $match: { labels: { $nin: [null, ""] } } },
            {
                $group: {
                    _id: { t: "$template", l: "$labels" },
                    count: { $sum: 1 },
                },
            },
            { $match: { count: { $gte: MIN_COUNT } } },
            {
                $group: {
                    _id: "$_id.t",
                    fields: { $addToSet: "$_id.l" },
                },
            },
            { $sort: { _id: 1 } },
        ],
        { allowDiskUse: true }
    )
    .toArray();

print(`Found ${results.length} templates`);

function escapeCSharp(s) {
    return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

const lines = [];
lines.push("// <auto-generated>");
lines.push(
    "// Generated from raw.pages infobox field distribution by"
);
lines.push(
    "// eng/scripts/generate-template-fields.mongodb.js."
);
lines.push("// Do not edit by hand -- regenerate with:");
lines.push(
    '//   mongosh "$MDB_MCP_CONNECTION_STRING" --quiet --file eng/scripts/generate-template-fields.mongodb.js'
);
lines.push(`// Source database: ${DB_NAME}.${COLL_NAME}`);
lines.push(`// Minimum field occurrence threshold: ${MIN_COUNT}`);
lines.push("// </auto-generated>");
lines.push("");
lines.push("namespace StarWarsData.Services.KnowledgeGraph.Definitions;");
lines.push("");
lines.push("/// <summary>");
lines.push("/// Per-template field whitelists inferred from the actual Wookieepedia");
lines.push("/// infobox data in MongoDB. Each template entry lists the distinct field");
lines.push("/// labels that appear on pages of that template type.");
lines.push("/// </summary>");
lines.push("public static class TemplateFields");
lines.push("{");
lines.push(
    "    public static readonly IReadOnlyDictionary<string, IReadOnlySet<string>> ByTemplate ="
);
lines.push(
    "        new Dictionary<string, IReadOnlySet<string>>(StringComparer.OrdinalIgnoreCase)"
);
lines.push("        {");

for (const doc of results) {
    const name = doc._id;
    if (!name) continue;
    const fields = (doc.fields || []).filter(Boolean).sort();
    if (fields.length === 0) continue;
    lines.push(
        `            ["${escapeCSharp(name)}"] = new HashSet<string>(StringComparer.OrdinalIgnoreCase)`
    );
    lines.push("            {");
    for (const field of fields) {
        lines.push(`                "${escapeCSharp(field)}",`);
    }
    lines.push("            },");
}

lines.push("        };");
lines.push("}");

const content = lines.join("\n") + "\n";
const fs = require("fs");
fs.writeFileSync(OUTPUT_PATH, content, "utf-8");

print(`Wrote ${OUTPUT_PATH}`);
print(`Templates: ${results.length}`);
print(`Lines: ${lines.length}`);
