namespace StarWarsData.Services.KnowledgeGraph.Definitions;

/// <summary>
/// Global semantic dictionary for infobox field labels.
/// For each known field label, this declares how to classify it:
/// as a scalar property, a typed relationship, or a temporal facet.
///
/// Template-level application is handled separately: <see cref="TemplateFields"/>
/// declares which fields each template actually has, and
/// <see cref="InfoboxDefinitionRegistry"/> intersects the two at lookup time.
///
/// Adding a new field: add one entry here, then ensure the field label is present
/// in TemplateFields for any template that should recognize it. TemplateFields is
/// auto-generated from MongoDB, so once a template starts using a field it will
/// appear in the whitelist on the next regeneration.
/// </summary>
internal static class FieldSemantics
{
    /// <summary>
    /// Field labels that should always be stored as scalar properties on the node.
    /// These are free-text, measurements, or enum-like values — never entity links.
    /// </summary>
    public static readonly IReadOnlySet<string> Properties = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        // Identity / titles
        "Titles",
        "Pronouns",
        "Listed pronouns",
        "Gender",
        "Nationality",
        "Occupation",
        // Physical attributes
        "Height",
        "Mass",
        "Weight",
        "Eye color",
        "Hair color",
        "Skin color",
        "Feather color",
        "Plating color",
        "Sensor color",
        "Color",
        "Blade color",
        "Average height",
        "Average length",
        "Average mass",
        "Average lifespan",
        "Average wingspan",
        "Physical description",
        "Distinctions",
        "Designation",
        "Classification",
        "Diet",
        "Habitat",
        "Other markings",
        "Heritage",
        "Cybernetics",
        "Demonym",
        // Descriptions / classifications
        "Class",
        "Model",
        "Shape",
        "Type",
        "Purpose",
        "Use(s)",
        "Size",
        "Value",
        "Organization type",
        "Type of group",
        "Type of deity",
        "Position type",
        "Title of leader",
        "Duties",
        "Alignment",
        "Physical description",
        "Genre",
        "Family type",
        // Measurements / specs
        "Length",
        "Width",
        "Height/depth",
        "Diameter",
        "Area",
        "Hyperdrive rating",
        "Maximum atmospheric speed",
        "Maximum speed",
        "Maximum speed (atmosphere)",
        "Megalight per hour",
        "Maximum altitude",
        "Maximum depth",
        "Maximum acceleration",
        "Range",
        "Passengers",
        "Population",
        "Consumables",
        "Cargo capacity",
        "Orbital position",
        "Orbital period",
        "Rotation period",
        "Surface water",
        "Dimensions",
        "Capacity",
        "Docking bays",
        "Atmosphere",
        "Terrain",
        "Climate",
        "Gravity",
        "Grid square",
        "Grid coordinates",
        "Major exports",
        "Major imports",
        "Other systems",
        // Ship specs (free-text)
        "Aliases",
        "Hull",
        "Life support",
        "Main computer",
        "Power plant",
        "Registration number(s)",
        "Minimum crew",
        "Crew",
        "Communication systems",
        "Cargo handling systems",
        "Countermeasures",
        "Targeting systems",
        "Primary role(s)",
        "Role(s)",
        "Equipment",
        "Degree",
        "Product line",
        "Line",
        "Protection type",
        "Hilt shape",
        "Substance type",
        "Properties",
        "Effects",
        "Modes",
        "Military unit type",
        "Formation type",
        "Strength",
        // Publication / media metadata
        "Pages",
        "Media type",
        "Issue number",
        "Issue #",
        "Issues",
        "Format",
        "Run time",
        "Discs",
        "Cassettes",
        "Number of players",
        "Ages of players",
        "Playing time",
        "Number of books",
        "Number of audiobooks",
        "Collected issues",
        "Skills required",
        "Platform(s)",
        "Production No",
        "Availability",
        "No. of cards",
        "No. of figures",
        // Outcomes / stats
        "Outcome",
        "Result",
        "Objective",
        "forces1",
        "forces2",
        "forces3",
        "forces4",
        "casual1",
        "casual2",
        "casual3",
        "casual4",
        "civilian",
        // Gameplay / product metadata
        "Galactic era(s)",
        "Official website",
        "Website",
        // Disease
        "Symptoms",
        "Transmission type",
        "Incubation period",
        "Number infected",
        "Number killed",
        "Cost",
        // Title / Position (Design-024 Phase B — TitleOrPositionNodeBuilder)
        "Powers",
        "Term length",
        // Phase C — ISBN normalisation (Book / ReferenceBook / ComicBook / MagazineIssue
        // builders). The wiki template emits the primary ISBN with an empty Label, so
        // it lands here under the canonical name "ISBN" via IsbnNormalizer post-pass.
        "ISBN",
        "ISBN2",
        "ISBN3",
    };

    /// <summary>
    /// Field labels that produce typed edges. Maps label → edge metadata
    /// (canonical name, reverse label, expected target types, description).
    /// </summary>
    public static readonly IReadOnlyDictionary<string, LabelDefinition> Relationships = new Dictionary<string, LabelDefinition>(StringComparer.OrdinalIgnoreCase)
    {
        // ── Character family / biological ──
        ["Species"] = new("species", "species_of", "Biological species", ["Species"], "biological"),
        ["Homeworld"] = new("homeworld", "homeworld_of", "Planet of origin", ["CelestialBody", "Location"], "location"),
        ["Homeworld(s)"] = new("homeworld", "homeworld_of", "Planet of origin", ["CelestialBody", "Location"], "location"),
        ["Point of origin"] = new("originates_from", "origin_of", "Place of origin", ["CelestialBody", "Location"], "location"),
        ["Origin"] = new("originates_from", "origin_of", "Place of origin", ["CelestialBody", "Location"], "location"),
        ["Place of origin"] = new("originates_from", "origin_of", "Place of origin", ["CelestialBody", "Location"], "location"),
        ["Place(s) of origin"] = new("originates_from", "origin_of", "Place of origin", ["CelestialBody", "Location"], "location"),
        ["Location of origin"] = new("originates_from", "origin_of", "Place of origin", ["CelestialBody", "Location"], "location"),
        ["Family"] = new("family", "includes_member", "Family group", ["Family"], "family"),
        ["Children"] = new("parent_of", "child_of", "Parent-of", ["Character", "Person"], "family"),
        ["Parent(s)"] = new("child_of", "parent_of", "Child-of", ["Character", "Person"], "family"),
        ["Sibling(s)"] = new("sibling_of", "sibling_of", "Sibling", ["Character", "Person"], "family"),
        ["Partner(s)"] = new("partner_of", "partner_of", "Romantic partner", ["Character", "Person"], "family"),
        ["Relatives"] = new("has_relative", "relative_of", "Extended family", ["Character", "Person"], "family"),
        ["Family head(s)"] = new("has_family_head", "family_head_of", "Family head", ["Character", "Person"], "family"),
        ["Masters"] = new("apprentice_of", "master_of", "Trained by", ["Character", "Person"], "mentorship"),
        ["Apprentices"] = new("master_of", "apprentice_of", "Trained", ["Character", "Person"], "mentorship"),
        ["Genetic donor(s)"] = new("cloned_from", "has_clone", "Clone source (forward: this clone was derived from the target)", ["Character", "Person"], "biological"),
        ["Subspecies"] = new("has_subspecies", "subspecies_of", "Subspecies", ["Species"], "biological"),
        ["Races"] = new("has_race", "race_of", "Racial subgroup", ["Species"], "biological"),
        ["Native species"] = new("has_native_species", "native_to", "Native species", ["Species"], "biological"),
        ["Other species"] = new("has_species", "lives_on", "Non-native species", ["Species"], "biological"),
        ["Other lifeforms"] = new("has_lifeform", "lives_on", "Non-species lifeforms", ["Species"], "biological"),
        ["Susceptible species"] = new("affects_species", "susceptible_to", "Species affected by disease", ["Species"], "biological"),
        ["Language"] = new("speaks_language", "spoken_by", "Language", ["Language"], "cultural"),
        ["Language(s)"] = new("speaks_language", "spoken_by", "Language", ["Language"], "cultural"),
        ["Primary language(s)"] = new("speaks_language", "spoken_by", "Primary language", ["Language"], "cultural"),
        ["Owner(s)"] = new("owned_by", "owns", "Owner", ["Character", "Person", "Organization"], "possession"),
        ["Owners"] = new("owned_by", "owns", "Owners", ["Character", "Person", "Organization"], "possession"),
        ["Users"] = new("used_by", "uses", "Users", ["Character", "Person"], "usage"),

        // ── Location / astronomy ──
        ["Region"] = new("in_region", "has_location", "Galactic region", ["Location"], "location"),
        ["Region(s)"] = new("in_region", "has_location", "Galactic region", ["Location"], "location"),
        ["Regions"] = new("in_region", "has_location", "Galactic regions", ["Location"], "location"),
        ["System"] = new("in_system", "has_celestial_body", "Star system", ["Location"], "location"),
        ["Systems"] = new("has_system", "in_sector", "Star systems", ["Location"], "location"),
        ["Sector"] = new("in_sector", "has_system", "Sector", ["Location"], "location"),
        ["Sectors"] = new("in_sector", "has_system", "Sectors", ["Location"], "location"),
        ["Orbited body"] = new("orbits", "orbited_by", "Body orbited", ["CelestialBody"], "astronomy"),
        ["Orbiting bodies"] = new("orbited_by", "orbits", "Orbiting bodies", ["CelestialBody"], "astronomy"),
        ["Orbit(s)"] = new("orbits", "orbited_by", "Body orbited", ["CelestialBody"], "astronomy"),
        ["Suns"] = new("orbits_star", "has_planet", "Central star(s)", ["Star"], "astronomy"),
        ["Moons"] = new("has_moon", "orbits", "Moons", ["CelestialBody"], "astronomy"),
        ["Asteroids"] = new("has_asteroid", "orbits", "Asteroids", ["CelestialBody"], "astronomy"),
        ["Comets"] = new("has_comet", "orbits", "Comets", ["CelestialBody"], "astronomy"),
        ["Nebulae"] = new("has_nebula", "in_region", "Nebulae", ["Nebula"], "astronomy"),
        ["Space stations"] = new("has_space_station", "orbits", "Space stations", ["SpaceStation"], "military"),
        ["Other objects"] = new("has_object", "in_system", "Other celestial objects", ["CelestialBody"], "astronomy"),
        ["Celestial body"] = new("on_celestial_body", "has_location", "Celestial body", ["CelestialBody"], "location"),
        ["Continent"] = new("on_continent", "has_location", "Continent", ["Location"], "location"),
        ["Flora"] = new("has_flora", "lives_on", "Native plants", ["Plant"], "biological"),
        ["Fauna"] = new("has_fauna", "lives_on", "Native animals", ["Species"], "biological"),
        ["Points of interest"] = new("has_point_of_interest", "located_at", "Notable locations", ["Location", "City"], "location"),
        ["Point(s) of interest"] = new("has_point_of_interest", "located_at", "Notable locations", ["Location", "City"], "location"),
        ["Major cities"] = new("has_city", "on_celestial_body", "Cities", ["City"], "location"),
        ["Trade routes"] = new("on_trade_route", "passes_through", "Trade routes", ["TradeRoute"], "economic"),
        ["Location"] = new("located_at", "has_location", "Location", ["Location", "CelestialBody", "City"], "location"),
        ["Location(s)"] = new("located_at", "has_location", "Locations", ["Location", "CelestialBody", "City"], "location"),
        ["Locations"] = new("located_at", "has_location", "Locations", ["Location", "CelestialBody", "City"], "location"),
        ["Other locations"] = new("located_at", "has_location", "Additional locations", ["Location", "CelestialBody", "City"], "location"),
        ["Found"] = new("found_at", "has_location", "Where found", ["Location", "CelestialBody"], "location"),
        ["Found on"] = new("found_at", "has_location", "Where found", ["Location", "CelestialBody"], "location"),
        ["Place of manufacture"] = new("manufactured_at", "manufactured_here", "Manufacturing location", ["Location", "City"], "location"),
        ["End points"] = new("has_endpoint", "endpoint_of", "Route endpoints", ["Location", "CelestialBody"], "location"),
        ["Junctions"] = new("has_junction", "junction_of", "Route junctions", ["Location", "TradeRoute"], "location"),

        // ── Political / organizational ──
        ["Affiliation"] = new("affiliated_with", "has_affiliate", "Affiliated organization", ["Organization", "Government"], "political"),
        ["Affiliation(s)"] = new("affiliated_with", "has_affiliate", "Affiliated organization", ["Organization", "Government"], "political"),
        ["Affiliated organizations"] = new("affiliated_with", "has_affiliate", "Affiliated organizations", ["Organization"], "political"),
        ["Affiliations involved"] = new("affiliated_with", "has_affiliate", "Affiliated organizations", ["Organization"], "political"),
        ["Associations"] = new("associated_with", "associated_with", "Associated organizations", ["Organization"], "political"),
        ["Leader(s)"] = new("led_by", "leads", "Leader", ["Character", "Person"], "political"),
        ["Mayor"] = new("led_by", "leads", "Mayor", ["Character", "Person"], "political"),
        ["Founder(s)"] = new("founded_by", "founded", "Founder", ["Character", "Person"], "political"),
        ["Founder"] = new("founded_by", "founded", "Founder", ["Character", "Person"], "political"),
        ["Established by"] = new("founded_by", "founded", "Establisher", ["Character", "Organization"], "political"),
        ["Head of state"] = new("head_of_state", "is_head_of", "Head of state", ["Character", "Person"], "political"),
        ["Head of government"] = new("head_of_government", "is_head_of", "Head of government", ["Character", "Person"], "political"),
        ["Commander-in-chief"] = new("commander_in_chief", "is_commander_of", "Commander-in-chief", ["Character", "Person"], "political"),
        ["Emperor"] = new("has_emperor", "emperor_of", "Emperor", ["Character", "Person"], "political"),
        ["Second-in-command"] = new("second_in_command", "second_of", "Second-in-command", ["Character", "Person"], "political"),
        ["Governing body"] = new("governed_by", "governs", "Governing body", ["Organization", "Government"], "political"),
        ["Government"] = new("governed_by", "governs", "Governing body", ["Organization", "Government"], "political"),
        ["Capital"] = new("has_capital", "capital_of", "Capital", ["City", "CelestialBody"], "political"),
        ["Headquarters"] = new("headquartered_at", "hosts_headquarters", "Headquarters", ["Location", "City", "CelestialBody"], "location"),
        ["Military branch"] = new("has_military_branch", "branch_of", "Military branch", ["Organization", "Military_unit"], "military"),
        ["Executive branch"] = new("has_executive_branch", "branch_of", "Executive branch", ["Organization"], "political"),
        ["Legislative branch"] = new("has_legislative_branch", "branch_of", "Legislative branch", ["Organization"], "political"),
        ["Judicial branch"] = new("has_judicial_branch", "branch_of", "Judicial branch", ["Organization"], "political"),
        ["Sub-group(s)"] = new("has_subgroup", "parent_group", "Subgroup", ["Organization"], "political"),
        ["Sub-groups"] = new("has_subgroup", "parent_group", "Subgroups", ["Organization"], "political"),
        ["Sub-units"] = new("has_subunit", "parent_unit", "Subordinate units", ["Military_unit"], "military"),
        ["Sects"] = new("has_sect", "sect_of", "Sects", ["Organization"], "religion"),
        ["Formed from"] = new("formed_from", "became", "Predecessor", ["Organization", "Government"], "political"),
        ["Parent company"] = new("subsidiary_of", "has_subsidiary", "Parent company", ["Company"], "economic"),
        ["Subsidiaries"] = new("has_subsidiary", "subsidiary_of", "Subsidiaries", ["Company"], "economic"),
        ["Currency"] = new("uses_currency", "used_by", "Currency", ["Currency"], "economic"),
        ["Official language"] = new("official_language", "official_language_of", "Official language", ["Language"], "cultural"),
        ["Constitution"] = new("has_constitution", "constitution_of", "Constitution", ["Law"], "political"),
        ["Founding document"] = new("has_founding_document", "founds", "Founding document", ["Law"], "political"),
        ["Official holiday"] = new("has_holiday", "observed_by", "Official holiday", ["Holiday"], "cultural"),
        ["Holidays"] = new("has_holiday", "observed_by", "Holidays", ["Holiday"], "cultural"),
        ["Anthem"] = new("has_anthem", "anthem_of", "Anthem", ["Music"], "cultural"),
        ["State religious body"] = new("has_state_religion", "state_religion_of", "State religion", ["Organization", "Religion"], "religion"),
        ["Major product(s)"] = new("produces", "produced_by", "Products", ["Device", "Weapon", "Starship"], "economic"),
        ["Members"] = new("has_member", "member_of", "Members", ["Character", "Person"], "political"),
        ["Notable members"] = new("has_notable_member", "notable_member_of", "Notable members", ["Character", "Person"], "political"),
        ["Notable units"] = new("has_notable_unit", "notable_unit_of", "Notable units", ["Military_unit"], "military"),
        ["Notable officer(s)"] = new("has_notable_officer", "notable_officer_of", "Notable officers", ["Character", "Person"], "military"),
        ["Staff officer(s)"] = new("has_staff_officer", "staff_officer_of", "Staff officers", ["Character", "Person"], "military"),
        ["Positions"] = new("has_position", "position_of", "Positions", ["TitleOrPosition"], "political"),
        ["Companies"] = new("works_for", "employs", "Companies", ["Company"], "economic"),
        ["Deities"] = new("worships_deity", "worshipped_by", "Worshipped deities", ["Deity"], "religion"),
        ["Holy text(s)"] = new("has_holy_text", "holy_text_of", "Holy texts", ["Book"], "religion"),
        ["Relics & artifacts"] = new("has_artifact", "artifact_of", "Sacred relics", ["Artifact"], "religion"),
        ["Relics &amp; artifacts"] = new("has_artifact", "artifact_of", "Sacred relics", ["Artifact"], "religion"),
        ["Artifacts"] = new("has_artifact", "artifact_of", "Artifacts", ["Artifact"], "religion"),
        ["Locations & temples"] = new("has_temple", "temple_of", "Sacred locations", ["Structure", "Location"], "religion"),
        ["Locations &amp; temples"] = new("has_temple", "temple_of", "Sacred locations", ["Structure", "Location"], "religion"),
        ["Ceremonies"] = new("has_ceremony", "ceremony_of", "Ceremonies", ["Event"], "religion"),
        ["Associated religion"] = new("associated_religion", "associated_entity", "Associated religion", ["Religion"], "religion"),
        ["Area of influence"] = new("influences", "influenced_by", "Area of influence", ["Location"], "religion"),
        ["Places of worship"] = new("worshipped_at", "hosts_worship", "Places of worship", ["Structure"], "religion"),
        ["Pantheon"] = new("in_pantheon", "includes_deity", "Pantheon", ["Religion"], "religion"),
        ["Treatments"] = new("treated_by", "treats", "Treatments", ["Substance", "Device"], "medical"),
        // Design-024 Phase C (C7): the survey shows ~95% of Culture / Socio-cultural
        // links resolve to Species or Religion, not CulturalGroup (which only has 34
        // total nodes). Widening the Targets array stops the generic-loop link filter
        // from silently dropping these as wrong-typed and keeps the dictionary honest
        // about the data shape.
        ["Culture"] = new("associated_culture", "culture_of", "Associated culture", ["Species", "Religion", "CulturalGroup"], "cultural"),
        ["Socio-cultural group(s)"] = new("associated_culture", "culture_of", "Socio-cultural group", ["Species", "Religion", "CulturalGroup"], "cultural"),

        // ── Combat / conflict ──
        ["Place"] = new("took_place_at", "hosted_battle", "Location of conflict", ["CelestialBody", "Location", "City", "Structure"], "location"),
        ["Conflict"] = new("part_of_conflict", "includes_battle", "Parent conflict", ["War", "Campaign"], "military"),
        ["Concurrent"] = new("concurrent_with", "concurrent_with", "Concurrent conflict", ["Battle", "War", "Mission", "Campaign"], "military"),
        ["Campaign"] = new("part_of_campaign", "includes_battle", "Parent campaign", ["Campaign"], "military"),
        ["Major battles"] = new("includes_battle", "part_of_conflict", "Notable battles", ["Battle"], "military"),
        ["Battles"] = new("includes_battle", "part_of_conflict", "Battles", ["Battle"], "military"),
        ["Notable battles"] = new("includes_battle", "part_of_conflict", "Notable battles", ["Battle"], "military"),
        ["side1"] = new("belligerent", "fought_in", "Side 1 faction", ["Organization", "Government", "Military_unit"], "military"),
        ["side2"] = new("belligerent", "fought_in", "Side 2 faction", ["Organization", "Government", "Military_unit"], "military"),
        ["side3"] = new("belligerent", "fought_in", "Side 3 faction", ["Organization", "Government", "Military_unit"], "military"),
        ["side4"] = new("belligerent", "fought_in", "Side 4 faction", ["Organization", "Government", "Military_unit"], "military"),
        ["commanders1"] = new("commanded_by", "commanded", "Side 1 commander", ["Character", "Person"], "military"),
        ["commanders2"] = new("commanded_by", "commanded", "Side 2 commander", ["Character", "Person"], "military"),
        ["commanders3"] = new("commanded_by", "commanded", "Side 3 commander", ["Character", "Person"], "military"),
        ["commanders4"] = new("commanded_by", "commanded", "Side 4 commander", ["Character", "Person"], "military"),
        ["Commander(s)"] = new("commanded_by", "commanded", "Commander", ["Character", "Person"], "military"),
        ["Commanding officer(s)"] = new("commanded_by", "commanded", "Commanding officer", ["Character", "Person"], "military"),
        ["unit1"] = new("unit_involved", "fought_in", "Side 1 unit", ["Military_unit", "Fleet"], "military"),
        ["unit2"] = new("unit_involved", "fought_in", "Side 2 unit", ["Military_unit", "Fleet"], "military"),
        ["unit3"] = new("unit_involved", "fought_in", "Side 3 unit", ["Military_unit", "Fleet"], "military"),
        ["unit4"] = new("unit_involved", "fought_in", "Side 4 unit", ["Military_unit", "Fleet"], "military"),
        ["ppl1"] = new("participants", "participated_in", "Side 1 participants", ["Character", "Person"], "military"),
        ["ppl2"] = new("participants", "participated_in", "Side 2 participants", ["Character", "Person"], "military"),
        ["ppl3"] = new("participants", "participated_in", "Side 3 participants", ["Character", "Person"], "military"),
        ["ppl4"] = new("participants", "participated_in", "Side 4 participants", ["Character", "Person"], "military"),
        ["Participants"] = new("has_participant", "participated_in", "Participants", ["Character", "Person"], "military"),
        ["Galactic Civil War"] = new("has_conflict", "happened_at", "Galactic Civil War events", ["Battle", "War"], "military"),
        ["Clone Wars"] = new("has_conflict", "happened_at", "Clone Wars events", ["Battle", "War"], "military"),
        ["Local conflict"] = new("has_conflict", "happened_at", "Local conflict", ["Battle", "War"], "military"),
        ["Conflicts"] = new("has_conflict", "happened_at", "Conflicts", ["Battle", "War"], "military"),
        ["Present for battles/events"] = new("present_for_battle", "had_present", "Present for battles", ["Battle"], "military"),

        // ── Technology / constructed objects ──
        ["Manufacturer"] = new("manufactured_by", "manufactures", "Manufacturer", ["Company", "Organization"], "economic"),
        ["Builder"] = new("built_by", "built", "Builder", ["Character", "Person", "Company"], "economic"),
        ["Builder(s)"] = new("built_by", "built", "Builders", ["Character", "Person", "Company"], "economic"),
        ["Designer"] = new("designed_by", "designed", "Designer", ["Character", "Person"], "creator"),
        ["Modified by"] = new("modified_by", "modified", "Modifier", ["Character", "Person"], "creator"),
        ["Created by"] = new("created_by", "created", "Creator", ["Character", "Person"], "creator"),
        ["Creator"] = new("created_by", "created", "Creator", ["Character", "Person"], "creator"),
        ["Creators"] = new("created_by", "created", "Creators", ["Character", "Person"], "creator"),
        ["Creator(s)"] = new("created_by", "created", "Creators", ["Character", "Person"], "creator"),
        ["Inventor"] = new("invented_by", "invented", "Inventor", ["Character", "Person"], "creator"),
        ["Armament"] = new("armed_with", "used_on", "Weapons systems", ["Weapon"], "military"),
        ["Engine unit(s)"] = new("has_engine", "engine_of", "Engines", ["Device"], "technology"),
        ["Hyperdrive system"] = new("has_hyperdrive", "hyperdrive_of", "Hyperdrive", ["Device"], "technology"),
        ["Shielding"] = new("has_shielding", "shielding_of", "Shielding", ["Device"], "technology"),
        ["Sensor systems"] = new("has_sensors", "sensors_of", "Sensors", ["Device"], "technology"),
        ["Navigation system"] = new("has_navigation", "navigation_of", "Navigation", ["Device"], "technology"),
        ["Complement"] = new("carries_complement", "carried_by", "Complement", ["Starship", "Vehicle"], "technology"),
        ["Material(s)"] = new("made_of", "used_in", "Materials", ["Substance"], "technology"),
        ["Crystal"] = new("has_crystal", "used_in", "Lightsaber crystal", ["Substance"], "technology"),
        ["Escape craft"] = new("has_escape_craft", "escape_craft_of", "Escape craft", ["Starship"], "technology"),
        ["Vehicles"] = new("has_vehicle", "used_by", "Vehicles used", ["Starship", "Vehicle"], "military"),
        ["Fleet"] = new("in_fleet", "has_ship", "Fleet", ["Fleet"], "military"),
        ["Navy"] = new("in_navy", "has_ship", "Navy", ["Organization", "Military_unit"], "military"),
        ["Flagship"] = new("has_flagship", "flagship_of", "Flagship", ["Starship"], "military"),
        ["Flagship(s)"] = new("has_flagship", "flagship_of", "Flagships", ["Starship"], "military"),
        ["Notable capital ships"] = new("has_notable_ship", "notable_ship_of", "Notable capital ships", ["Starship"], "military"),

        // ── Publication / media ──
        ["Publisher"] = new("published_by", "publishes", "Publisher", ["Company"], "publication"),
        ["Publisher(s)"] = new("published_by", "publishes", "Publishers", ["Company"], "publication"),
        ["Author(s)"] = new("authored_by", "authored", "Author", ["Character", "Person"], "publication"),
        ["Writer"] = new("written_by", "wrote", "Writer", ["Character", "Person"], "publication"),
        ["Writer(s)"] = new("written_by", "wrote", "Writers", ["Character", "Person"], "publication"),
        ["Penciller"] = new("illustrated_by", "illustrated", "Penciller", ["Character", "Person"], "publication"),
        ["Penciller(s)"] = new("illustrated_by", "illustrated", "Pencillers", ["Character", "Person"], "publication"),
        ["Illustrator"] = new("illustrated_by", "illustrated", "Illustrator", ["Character", "Person"], "publication"),
        ["Illustrator(s)"] = new("illustrated_by", "illustrated", "Illustrators", ["Character", "Person"], "publication"),
        ["Colorist"] = new("colored_by", "colored", "Colorist", ["Character", "Person"], "publication"),
        ["Colorist(s)"] = new("colored_by", "colored", "Colorists", ["Character", "Person"], "publication"),
        ["Letterer"] = new("lettered_by", "lettered", "Letterer", ["Character", "Person"], "publication"),
        ["Letterer(s)"] = new("lettered_by", "lettered", "Letterers", ["Character", "Person"], "publication"),
        ["Inker"] = new("inked_by", "inked", "Inker", ["Character", "Person"], "publication"),
        ["Inker(s)"] = new("inked_by", "inked", "Inkers", ["Character", "Person"], "publication"),
        ["Cover artist"] = new("cover_by", "cover_artist_of", "Cover artist", ["Character", "Person"], "publication"),
        ["Cover artist(s)"] = new("cover_by", "cover_artist_of", "Cover artists", ["Character", "Person"], "publication"),
        ["Editor"] = new("edited_by", "edited", "Editor", ["Character", "Person"], "publication"),
        ["Editor(s)"] = new("edited_by", "edited", "Editors", ["Character", "Person"], "publication"),
        ["Narrator(s)"] = new("narrated_by", "narrated", "Narrator", ["Character", "Person"], "publication"),
        ["Director(s)"] = new("directed_by", "directed", "Director", ["Character", "Person"], "publication"),
        ["Producer(s)"] = new("produced_by", "produced", "Producer", ["Character", "Person"], "publication"),
        ["Composer(s)"] = new("composed_by", "composed", "Composer", ["Character", "Person"], "publication"),
        ["Developer(s)"] = new("developed_by", "developed", "Developer", ["Company"], "publication"),
        ["Performer(s)"] = new("performed_by", "performed", "Performer", ["Character", "Person"], "publication"),
        ["Contributor(s)"] = new("contributed_by", "contributed_to", "Contributors", ["Character", "Person"], "publication"),
        ["Series"] = new("part_of_series", "includes", "Series", ["ComicSeries", "BookSeries"], "publication"),
        ["Published in"] = new("published_in", "publishes", "Publication venue", ["MagazineIssue", "ComicBook"], "publication"),
        ["Timeline"] = new("in_timeline", "includes", "Timeline", ["Era"], "publication"),
        ["Reprinted in"] = new("reprinted_in", "reprints", "Reprint venue", ["Book", "ComicBook"], "publication"),
        ["Game"] = new("for_game", "includes", "Game", ["Game", "VideoGame"], "publication"),
        ["Episode"] = new("part_of_episode", "includes", "Episode", ["TelevisionEpisode"], "publication"),
        ["Next episode"] = new("next_episode", "prior_episode", "Next episode", ["TelevisionEpisode"], "publication"),
        ["Prior episode"] = new("prior_episode", "next_episode", "Prior episode", ["TelevisionEpisode"], "publication"),
        ["Season"] = new("part_of_season", "includes", "Season", ["TelevisionSeason"], "publication"),

        // ── Sequence (common) ──
        ["Next"] = new("followed_by", "preceded_by", "Next in sequence", [], "sequence"),
        ["Previous"] = new("preceded_by", "followed_by", "Previous in sequence", [], "sequence"),
        ["Followed by"] = new("followed_by", "preceded_by", "Next in sequence", [], "sequence"),
        ["Preceded by"] = new("preceded_by", "followed_by", "Previous in sequence", [], "sequence"),
        ["Subsequent"] = new("followed_by", "preceded_by", "Next in sequence", [], "sequence"),
        ["Part of"] = new("part_of", "contains", "Part of larger entity", [], "composition"),

        // ── Misc ──
        ["Years"] = new("spans_years", "in_era", "Years spanned", ["Year"], "temporal"),
        ["Important events"] = new("has_important_event", "happened_in", "Notable events", ["Event"], "temporal"),
        ["Events"] = new("has_event", "happened_in", "Events", ["Event"], "temporal"),
        ["Goods"] = new("has_goods", "made_in", "Trade goods", ["Substance", "Food"], "economic"),
        ["Candidates"] = new("has_candidate", "ran_in", "Candidates", ["Character", "Person"], "political"),
        ["Electorate"] = new("has_electorate", "elected_by", "Electorate", ["Organization"], "political"),
        ["Competitors"] = new("has_competitor", "competed_in", "Competitors", ["Character", "Person"], "sports"),
        ["League"] = new("in_league", "includes_team", "League", ["Organization"], "sports"),
        ["Organizer(s)"] = new("organized_by", "organized", "Organizer", ["Character", "Person", "Organization"], "sports"),
        ["Host(s)"] = new("hosted_by", "hosted", "Host", ["Character", "Person", "Organization"], "sports"),
        ["Songs"] = new("performs_song", "performed_by", "Songs performed", ["Music"], "music"),
        ["Collaborations"] = new(
            "collaborates_with",
            "collaborates_with",
            "Music collaborators (band/musician/composer field — NOT for general character interactions)",
            ["Character", "Person", "Band"],
            "music"
        ),
        ["Edible by"] = new("edible_by", "eats", "Edible by", ["Species"], "food"),
        ["Potable by"] = new("potable_by", "drinks", "Potable by", ["Species"], "food"),
        ["Dishes"] = new("has_dish", "part_of_cuisine", "Dishes", ["Food"], "food"),
        ["Other ingredients"] = new("has_ingredient", "used_in", "Other ingredients", ["Food"], "food"),
        ["Plant-based ingredients"] = new("has_ingredient", "used_in", "Plant ingredients", ["Plant"], "food"),
        ["Animal-based ingredients"] = new("has_ingredient", "used_in", "Animal ingredients", ["Species"], "food"),
        ["Awarded by"] = new("awarded_by", "awarded", "Awarding body", ["Organization"], "honors"),

        // ── Design-024 Phase B additions ──
        // Sector field-alias collapse (SectorNodeBuilder): wiki uses these distinct
        // labels on Sector pages but the semantic relationship is uniform.
        ["Sector capital"] = new("has_capital", "capital_of", "Sector capital", ["City", "CelestialBody"], "political"),
        ["Subsectors"] = new("has_subsector", "parent_sector", "Subsectors of this sector", ["Sector"], "location"),
        ["Stations"] = new("has_space_station", "orbits", "Space stations in this sector", ["SpaceStation"], "military"),
        // Year typed-leader fields (DefaultNodeBuilder for Year): Year pages list named leadership
        // positions held during that year. Survey: 134 Chancellor, 43 Chief, 25 Head edges.
        ["Chancellor"] = new("has_chancellor", "chancellor_of", "Chancellor in office", ["Character", "Person"], "political"),
        ["Head"] = new("has_head", "head_of", "Head of state in office", ["Character", "Person"], "political"),
        ["Chief"] = new("has_chief", "chief_of", "Chief of state in office", ["Character", "Person"], "political"),
        // Source × target relabel seeds (CharacterNodeBuilder, DroidNodeBuilder,
        // TitleOrPositionNodeBuilder). The keys are synthetic — they are NEVER
        // matched against an infobox field (no template has a field literally
        // named "__has_role"). Their purpose is to register the canonical label +
        // reverse + description in FieldSemantics.Relationships so kg.labels
        // exposes them with a meaningful entry once OnFinalize emits them. The
        // leading "__" makes the synthetic origin obvious in mongosh.
        // Labels already covered by existing entries (member_of via Members's
        // reverse pair, owned_by via Owner(s), works_for via Companies) don't need
        // a new seed — the existing description still applies.
        ["__has_role"] = new("has_role", "held_by", "Role / position assigned to a character", ["TitleOrPosition"], "role"),
        ["__member_of_family"] = new("member_of_family", "has_family_member", "Family membership", ["Family"], "family"),
        ["__has_ethnicity"] = new("has_ethnicity", "ethnicity_of", "Ethnic / sub-species heritage", ["Species"], "cultural"),
        ["__from_city"] = new("from_city", "origin_city_of", "City of origin", ["City"], "location"),
        ["__serves_in_unit"] = new("serves_in", "has_member", "Military service — serves in unit / fleet", ["Military_unit", "Fleet"], "military"),
        ["__position_in"] = new("position_in", "has_position", "Position-in-organization (TitleOrPosition only)", ["Organization", "Government"], "political"),

        // ── Design-024 Phase C additions ──
        // C1 — CelestialBody source-aware language relabel: planets don't speak,
        // but they do "host" a language community.
        ["__has_language"] = new("has_language", "language_of", "Primary language used on a celestial body / system", ["Language"], "cultural"),
        // C2 — TelevisionEpisode promotions
        ["Guest star(s)"] = new("featured_actor", "acted_in", "Guest-starring actor in a TV episode", ["Person", "Character"], "publication"),
        ["Production company"] = new("produced_by", "produced", "Production company that made the work", ["Company"], "publication"),
        // C4 — ReferenceMagazine "Featured" content
        ["Featured"] = new("features", "featured_in", "Subject featured in a publication", ["Character", "Person", "Organization", "CelestialBody"], "publication"),
        // C5 — IndividualShip / StarshipClass affiliation refinements
        ["__assigned_to"] = new("assigned_to", "has_assignment", "Ship / unit assignment to a fleet or military unit", ["Military_unit", "Fleet"], "military"),
        ["__designed_for"] = new("designed_for", "design_target_of", "Ship class designed for / by a species or religion", ["Species", "Religion"], "military"),
        // C8 — Food: merge "Race" alias into Edible-by semantics, and add "Inedible by".
        // "Race" maps to the same semantic as "Edible by" (the Wookieepedia field is
        // an old synonym for the species that can eat the food).
        ["Race"] = new("edible_by", "eats", "Species that can eat this food (alias for Edible by)", ["Species"], "food"),
        ["Inedible by"] = new("not_edible_by", "cannot_eat", "Species for which the food is poisonous or otherwise unsafe", ["Species"], "food"),
        // C9 — Character Yuuzhan Vong concepts (small but real). Promoted from
        // unclassified silent-text to typed edges. Both are Religion-typed targets
        // in the data — the Yuuzhan Vong domain/caste structure is part of their
        // religious cosmology — so the Religion target list applies.
        ["Domain"] = new("has_domain", "domain_of", "Yuuzhan Vong domain affiliation", ["Religion", "Organization"], "cultural"),
        ["Caste"] = new("has_caste", "caste_of", "Yuuzhan Vong caste affiliation", ["Religion", "Organization"], "cultural"),
    };

    /// <summary>
    /// Field labels that produce temporal facets on the node.
    /// Maps label → (semantic dimension, calendar hint).
    /// </summary>
    public static readonly IReadOnlyDictionary<string, TemporalFieldDefinition> TemporalFields = new Dictionary<string, TemporalFieldDefinition>(StringComparer.OrdinalIgnoreCase)
    {
        // Lifespan
        ["Born"] = new("lifespan.start", "auto"),
        ["Died"] = new("lifespan.end", "auto"),
        // Conflict
        ["Date"] = new("conflict.point", "galactic"),
        ["Begin"] = new("conflict.start", "galactic"),
        ["Begins"] = new("conflict.start", "galactic"),
        ["Beginning"] = new("conflict.start", "galactic"),
        ["End"] = new("conflict.end", "galactic"),
        ["Ends"] = new("conflict.end", "galactic"),
        // Construction
        ["Constructed"] = new("construction.start", "galactic"),
        ["Commissioned"] = new("construction.start", "galactic"),
        ["Rebuilt"] = new("construction.rebuilt", "galactic"),
        ["Destroyed"] = new("construction.end", "galactic"),
        ["Retired"] = new("construction.end", "galactic"),
        // Creation
        ["Date created"] = new("creation.start", "galactic"),
        ["Date engineered"] = new("creation.start", "galactic"),
        ["Date introduced"] = new("creation.start", "galactic"),
        ["Year introduced"] = new("creation.start", "galactic"),
        ["Date destroyed"] = new("creation.end", "galactic"),
        ["Date retired"] = new("creation.end", "galactic"),
        ["Date discovered"] = new("creation.discovered", "galactic"),
        // Institutional lifecycle
        ["Date established"] = new("institutional.start", "galactic"),
        ["Date founded"] = new("institutional.start", "galactic"),
        ["Founding"] = new("institutional.start", "galactic"),
        ["Founded"] = new("institutional.start", "auto"),
        ["Established"] = new("institutional.start", "galactic"),
        ["Date dissolved"] = new("institutional.end", "galactic"),
        ["Dissolved"] = new("institutional.end", "auto"),
        ["Date abolished"] = new("institutional.end", "galactic"),
        ["Date of collapse"] = new("institutional.end", "galactic"),
        ["Closed"] = new("institutional.end", "auto"),
        ["Date closed"] = new("institutional.end", "auto"),
        ["Date reorganized"] = new("institutional.reorganized", "galactic"),
        ["Reorganized"] = new("institutional.reorganized", "galactic"),
        ["Reorganization"] = new("institutional.reorganized", "galactic"),
        ["Date restored"] = new("institutional.restored", "galactic"),
        ["Restored"] = new("institutional.restored", "galactic"),
        ["Date reestablished"] = new("institutional.restored", "galactic"),
        ["Date of restoration"] = new("institutional.restored", "galactic"),
        ["Date fragmented"] = new("institutional.fragmented", "galactic"),
        ["Fragmented"] = new("institutional.fragmented", "galactic"),
        ["Fragmentation"] = new("institutional.fragmented", "galactic"),
        ["Date suspended"] = new("institutional.suspended", "galactic"),
        // Publication (always real-world)
        ["Release date"] = new("publication.release", "real"),
        ["Publication date"] = new("publication.release", "real"),
        ["Air date"] = new("publication.release", "real"),
        ["First released"] = new("publication.release", "real"),
        ["Released"] = new("publication.release", "real"),
        ["Premiere date"] = new("publication.release", "real"),
        ["Launched"] = new("publication.release", "real"),
        ["Rerelease date(s)"] = new("publication.release", "real"),
        ["International release date(s)"] = new("publication.release", "real"),
        ["International releases"] = new("publication.release", "real"),
        ["International release"] = new("publication.release", "real"),
        ["Early release date"] = new("publication.release", "real"),
        ["Early screening"] = new("publication.release", "real"),
        ["Start date"] = new("publication.start", "real"),
        ["First aired"] = new("publication.start", "real"),
        ["First published"] = new("publication.start", "real"),
        ["First book published"] = new("publication.start", "real"),
        ["First media published"] = new("publication.start", "real"),
        ["First issue"] = new("publication.start", "real"),
        ["End date"] = new("publication.end", "real"),
        ["Last aired"] = new("publication.end", "real"),
        ["Last published"] = new("publication.end", "real"),
        ["Last book published"] = new("publication.end", "real"),
        ["Last issue"] = new("publication.end", "real"),
        ["Closing date"] = new("publication.end", "real"),
        // Usage
        ["First awarded"] = new("usage.start", "galactic"),
        ["Last awarded"] = new("usage.end", "galactic"),
        ["First employed"] = new("usage.start", "galactic"),
        ["Last employed"] = new("usage.end", "galactic"),
        ["First played"] = new("usage.start", "galactic"),
        ["First worshipped"] = new("usage.start", "galactic"),
        // Era span — the value string contains multiple BBY/ABY years forming
        // a range (e.g. "25,000 BBY – 19 BBY"). IsRange=true tells the extractor
        // to emit one facet per year, with roles era.start/era.end/era.point.
        ["Years"] = new("era", "galactic", IsRange: true),
    };
}
